name: Mini-Pay CI í…ŒìŠ¤íŠ¸ ìë™í™”

on:
  pull_request:
    branches: "base/youngtae"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: JDK 17ì„ ì„¤ì¹˜í•©ë‹ˆë‹¤
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Wrapper íŒŒì¼ ë° ê¶Œí•œ í™•ì¸
        run: |
          echo "Listing files in the directory:"
          ls -al
          echo "Setting execute permissions for gradlew"
          chmod +x gradlew

      - name: ë¹Œë“œ ì‹œ ìºì‹œ ì ìš©
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: ë¹Œë“œ
        run: ./gradlew build jacocoTestReport

      - name: í…ŒìŠ¤íŠ¸ ì»¤ë²„ë¦¬ì§€ë¥¼ PRì— ì½”ë©˜íŠ¸ë¡œ ë“±ë¡í•©ë‹ˆë‹¤
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          title: ğŸ“ í…ŒìŠ¤íŠ¸ ì»¤ë²„ë¦¬ì§€ ë¦¬í¬íŠ¸ì…ë‹ˆë‹¤
          paths: ${{ github.workspace }}/build/reports/jacoco/test/html/index.html
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80
